export const adminCopy = {
  login: {
    title: "CCA Registration System",
    fields: {
      email: "Email",
      password: "Password",
    },
    submit: "Sign In",
    invalidCredentials: "Invalid credentials",
  },
  dashboard: {
    identity: "CCA Registration System",
    title: "Admin Dashboard",
    logout: "Logout",
    addRecord: "Add Record",
    searchPlaceholder: "Search students...",
    diplomaFilter: "All Bootcamps",
    paymentFilter: "All Payment Methods",
    paymentOptions: {
      online: "Online Payment",
      slip: "Bank Slip",
      study_now_pay_later: "Study Now Pay Later",
    },
    search: "Search",
    clear: "Clear",
    showing: "Showing {first} - {last} of {total} students",
    headers: [
      "Registration ID",
      "Full Name",
      "Selected Bootcamp",
      "NIC",
      "WhatsApp",
      "Payment",
      "Actions",
    ],
    status: {
      success: "Payment Success",
      pending: "Payment Pending",
      slipApproved: "Slip Approved",
      slipPending: "Slip Pending",
      studyNowPayLater: "Pending Exam Fee",
      notSet: "Not set",
      viewSlip: "View Slip",
      noSlip: "No slip",
    },
    approve: {
      action: "Approve Slip",
      working: "Approving...",
      error: "Unable to approve this slip right now. Please try again.",
    },
    uploadSlip: {
      action: "Upload Slip",
      working: "Uploading...",
      error: "Unable to upload this slip right now. Please try again.",
      attached: "Slip uploaded",
    },
    emptyTitle: "No students found",
    emptyBody: "Try adjusting your search criteria",
    previous: "Previous",
    next: "Next",
    viewModalTitle: "Student Details",
    delete: {
      title: "Delete Registration",
      body: "Are you sure you want to delete {name} and any related program records under the same registration?",
      warning:
        "This will also delete the payment slip image if available. This action cannot be undone.",
      error: "Unable to delete this registration right now. Please try again.",
      label: "Type DELETE to confirm:",
      placeholder: "Type DELETE",
      cancel: "Cancel",
      confirm: "Delete",
    },
  },
  create: {
    title: "Add Student Record",
    subtitle: "Create a manual registration with one or two bootcamps.",
    save: "Create Record",
    saving: "Creating...",
    back: "Back",
    error: "Unable to create the student record right now.",
    sections: {
      student: "Student details",
      registration: "Programs and payment",
      notes: "How this works",
    },
    paymentSetup: {
      label: "Payment Setup *",
      options: {
        online_completed: "Online Payment Completed",
        slip_pending: "Bank Slip Pending Review",
        slip_approved: "Bank Slip Approved",
        study_now_pay_later: "Study Now Pay Later",
      },
      helper:
        "Choose the state that best matches the record you are adding. This creates the full registration group immediately.",
    },
    bootcamps: {
      label: "Selected Bootcamps *",
      helper: "Choose one or two bootcamps for this registration.",
      limit: "You can select up to two bootcamps only.",
    },
    notes: [
      "One bootcamp creates one row. Two bootcamps create a grouped registration with two rows.",
      "Manual records do not send SMS and do not create a public session.",
      "Slip records without an uploaded file can still be saved, but only uploaded slips can be approved from the dashboard action.",
    ],
    created: "Student record created successfully.",
  },
  edit: {
    identity: "CCA Registration System",
    title: "Edit Student Information",
    back: "Back to Dashboard",
    pageTitle: "Edit Student Record",
    pageSubtitle: "Update student information and details",
    sectionTitle: "Student Information",
    paymentTitle: "Payment Information (Read Only)",
    labels: {
      full_name: "Full Name *",
      name_with_initials: "Name with Initials",
      gender: "Gender *",
      nic: "NIC Number *",
      date_of_birth: "Date of Birth *",
      whatsapp_number: "WhatsApp Number",
      home_contact_number: "Emergency Contact Number (Home Number) *",
      email: "Email Address *",
      permanent_address: "Permanent Address",
      postal_code: "Postal Code",
      district: "District",
      districtPlaceholder: "Select District",
      selected_diploma: "Selected Bootcamp *",
      diplomaPlaceholder: "Select a bootcamp",
      registration_id: "Registration ID",
      payment_method: "Payment Method",
      payment_status: "Payment Status",
      amount_paid: "Amount Paid",
    },
    actions: {
      cancel: "Cancel",
      submit: "Update Student",
    },
  },
};
