export const adminCopy = {
  login: {
    title: "CCA Registration System",
    fields: {
      email: "Email",
      password: "Password",
    },
    submit: "Sign In",
    invalidCredentials: "Invalid credentials",
  },
  dashboard: {
    identity: "CCA Registration System",
    title: "Admin Dashboard",
    logout: "Logout",
    searchPlaceholder: "Search students...",
    diplomaFilter: "All Bootcamps",
    paymentFilter: "All Payment Methods",
    paymentOptions: {
      online: "Online Payment",
      slip: "Bank Slip",
      study_now_pay_later: "Study Now Pay Later",
    },
    search: "Search",
    clear: "Clear",
    showing: "Showing {first} - {last} of {total} students",
    headers: [
      "Registration ID",
      "Full Name",
      "Selected Bootcamp",
      "NIC",
      "WhatsApp",
      "Payment Slip",
      "Actions",
    ],
    status: {
      success: "Payment Success",
      pending: "Payment Pending",
      viewSlip: "View Slip",
      noSlip: "No slip",
    },
    emptyTitle: "No students found",
    emptyBody: "Try adjusting your search criteria",
    previous: "Previous",
    next: "Next",
    viewModalTitle: "Student Details",
    delete: {
      title: "Delete Student",
      body: "Are you sure you want to delete {name}?",
      warning:
        "This will also delete the payment slip image if available. This action cannot be undone.",
      label: "Type DELETE to confirm:",
      placeholder: "Type DELETE",
      cancel: "Cancel",
      confirm: "Delete",
    },
  },
  edit: {
    identity: "CCA Registration System",
    title: "Edit Student Information",
    back: "Back to Dashboard",
    pageTitle: "Edit Student Record",
    pageSubtitle: "Update student information and details",
    sectionTitle: "Student Information",
    paymentTitle: "Payment Information (Read Only)",
    labels: {
      full_name: "Full Name *",
      name_with_initials: "Name with Initials",
      gender: "Gender *",
      nic: "NIC Number *",
      date_of_birth: "Date of Birth *",
      whatsapp_number: "WhatsApp Number",
      home_contact_number: "Emergency Contact Number (Home Number) *",
      email: "Email Address *",
      permanent_address: "Permanent Address",
      postal_code: "Postal Code",
      district: "District",
      districtPlaceholder: "Select District",
      selected_diploma: "Selected Bootcamp *",
      diplomaPlaceholder: "Select a bootcamp",
      registration_id: "Registration ID",
      payment_method: "Payment Method",
      payment_status: "Payment Status",
      amount_paid: "Amount Paid",
    },
    actions: {
      cancel: "Cancel",
      submit: "Update Student",
    },
  },
};
