export const publicCopy = {
  titleFallback: "Student Registration",
  countdown: {
    label: "Limited Time Opportunity",
    title: "Registration Closes In:",
    subtitle: "Complete your form before time runs out",
    labels: ["Days", "Hours", "Minutes", "Seconds"],
    shortLabels: ["Days", "Hrs", "Min", "Sec"],
    paymentTitle: "Complete Payment Before",
    paymentSubtitle: "Choose your payment method below",
  },
  home: {
    title: "Special Scholarship Opportunity",
    subtitle:
      "Register now for the special opportunity to get a Rs. 10,000 discount on your bootcamp program.",
    cta: "Choose Your Bootcamps",
    imageAlt: "Convocation Ceremony",
    propositions: [
      "මෙහි එක් සමස්ත පාඨමාලාවක් සඳහාම සාමාන්‍යයෙන් අය කෙරෙන මුළු ගාස්තුව **රු. 28,000 ක්** පමණි. නමුත් ඔබට විශේෂ 'නිපුණතා ශිෂ්‍යත්වය' යටතේ **රු. 10,000ක සුවිශේෂී වට්ටමක්** හිමි කර ගත හැකිය.",
      "මෙහිදී **10,000 ක අමතර ශිෂ්‍යත්වයක්** නිපුණතා ශිෂ්‍යත්ව අරමුදල මගින් ඔබ ඇතුළු තොරාගත් සිසුන් කිහිප දෙනෙකුට ලබා දෙනු ලැබේ. ඒ අනුව ඔබ ගෙවිය යුතු මුළු මුදල වන්නේ **රු. 18,000 පමණී.**",
      "දැන් ඔබට **රුපියල් 3,000ක මුදලක් පමණක්** ගෙවා ලියාපදිංචි වී ඔබගේ ඉගෙනීම් කටපුතු ආරම්භ කළ හැකිය. ඉතිරි **රු. 15,000** පාඨමාලා ගාස්තුව සිසුන් ගෙවිය යුත්තේ **වාරික කොටස් දෙකක් වශයෙන්ය.** ඉන් පසු ද ඉගෙනීම් කටයුතු සදහා හෝ Internships සොයාදීම හෝ ලබාදීම සදහා කිසිවිටෙකත් කිසිදු අමතර මුදලක් ගෙවිය යුතු නැත.",
    ],
  },
  selectBootcamp: {
    title: "Choose Your Bootcamp Programs",
    subtitle: "Select one or two bootcamp programs that best match your goals.",
    cta: "Continue with Selected Bootcamps",
  },
  eligibility: {
    eyebrow: "Registration Open",
    title: "දැන්ම ලියාපදිංචි වන්න",
    questionSuffix: "Bootcamp Batch සදහා දැනටමත් ලියාපදිංචි වී සිටීද?",
    subtitle:
      "Please select your answer to continue with the registration process",
    yes: "Yes",
    no: "No",
    yesCardTitle: "Thank You for Your Interest!",
    yesCardBody:
      "We appreciate your enthusiasm. However, as you have just started a new bootcamp program, you are not eligible for this scholarship scheme on this particular program this time.",
    yesCardNext: "What's Next?",
    yesCardNextBody: "Stay tuned for our next intake opening.",
    noCardTitle: "Perfect! Let's Get Started",
    noCardBody:
      "You're eligible to register. Click below to begin your educational journey with us!",
    noCardCta: "Continue to Registration",
  },
  register: {
    progressTitle: "Registration Progress",
    step: "Step 1 of 3",
    steps: ["Details", "Payment", "Complete"],
    badge: "Selected Program",
    title: "Student Registration Details",
    subtitle: "Please fill out the form accurately.",
    errorsTitle: "Please fix the following errors:",
    fields: {
      registration_id: {
        label: "Register ID *",
        helper:
          "Your unique registration ID. Please save this for future reference.",
      },
      full_name: {
        label: "Full Name *",
        placeholder: "Enter Full Name as per NIC/Passport",
      },
      name_with_initials: {
        label: "Name With Initials *",
        placeholder: "Enter Name with Initials",
      },
      gender: {
        label: "Gender *",
        placeholder: "Select Gender",
        options: { male: "Male", female: "Female" },
      },
      date_of_birth: { label: "Date of Birth *" },
      nic: {
        label: "National ID Number *",
        placeholder: "Enter valid NIC (e.g., 95xxxxxxxV or 200xxxxxxxx)",
        hints: [
          "Old Format: 9 digits + V/X (e.g., 123456789V)",
          "New Format: 12 digits (e.g., 200012345678)",
        ],
      },
      email: { label: "Email Address *", placeholder: "you@example.com" },
      permanent_address: {
        label: "Permanent Address *",
        placeholder: "Enter your full permanent address",
      },
      postal_code: {
        label: "Postal Code (Optional)",
        placeholder: "e.g., 10200",
      },
      district: { label: "District *", placeholder: "Select District" },
      home_contact_number: {
        label: "Emergency Contact Number (Home Number) *",
        placeholder: "e.g., 0112XXXXXX",
      },
      whatsapp_number: {
        label: "WhatsApp Number *",
        placeholder: "e.g., 07XXXXXXXX (Active number)",
      },
      terms_accepted:
        "I confirm that the information provided is accurate and I agree to the terms and conditions provided by CCA Campus via their support channels. *",
    },
    actions: {
      submit: "Continue to Register",
      back: "Back",
    },
    help: {
      title: "Need Help?",
      body: "If you have any questions or need assistance with the registration process, please contact our support team via WhatsApp at",
    },
    courseCard: {
      title: "Want to Know More?",
      body: "View complete course details, syllabus, and program information for your selected bootcamps.",
      cta: "View Course Details",
    },
    nicMessages: {
      valid: "✓ Valid Sri Lankan NIC",
      invalidFormat:
        "Invalid NIC format. Use either 9 digits + V/X or 12 digits.",
      invalidDay: "Invalid day of year in NIC.",
      invalidYear: "Invalid birth year in NIC.",
    },
  },
  paymentOptions: {
    progressTitle: "Registration Progress",
    step: "Step 2 of 3",
    registrationDetails: "Registration Details",
    summaryLabels: [
      "Registration ID",
      "Full Name",
      "Name with Initials",
      "Gender",
      "NIC",
      "Date of Birth",
      "Email",
      "Bootcamp(s)",
      "WhatsApp Number",
      "Emergency Contact",
      "District",
      "Postal Code",
      "Permanent Address",
      "Course Duration",
    ],
    courseDuration: "6 Months",
    blockTitle: "Choose a Payment Method",
    agreementTitle: "Confirm Your Details",
    agreementLabels: ["Full Name", "NIC Number"],
    onlineTitle: "Card Payment",
    onlineBody: "Pay the registration fee securely using your debit or credit card.",
    onlineCta: "Pay with Card",
    slipTitle: "Bank Transfer",
    slipBody: "Transfer the registration fee to our bank account and upload the payment slip.",
    slipCta: "Bank Transfer / Upload Slip",
    back: "Back to Registration Details",
    bullets: [
      "This certification is accredited by Distance Education Council (DEC) under the Ministry of Industry in Sri Lanka and the SITC Campus. There are no any additional fees for the certificate or experience completion letter.",
      "Start your learning journey for just Rs. 3,000 per program! While the full course fee is Rs. 18,000 per program after the special scholarship discount, we offer a flexible payment plan where the remaining Rs. 15,000 is split into two easy installments. Plus, there are absolutely no hidden costs for study materials or internship placements.",
    ],
  },
  uploadSlip: {
    step: "Step 3 of 3",
    pageLabel: "Upload Slip",
    title: "Upload Payment Slip",
    subtitle: "Complete your registration",
    registrationDetails: "Registration Details",
    labels: {
      registrationId: "Registration ID",
      studentName: "Student Name",
      selectedDiploma: "Selected Program(s)",
      amountToPay: "Total Amount to Pay",
      amount: "LKR 3,000 per program",
    },
    bankTitle: "Bank Transfer Details",
    bankSubtitle: "You can transfer to any of these bank accounts:",
    bankLabels: {
      accountNumber: "Account Number:",
      accountName: "Account Name:",
      branch: "Branch:",
    },
    warningAmount: "Amount to Transfer: LKR 3,000 per program",
    warningReference:
      "Please include or write your first name in the payment slip for reference",
    uploadTitle: "Upload Payment Slip",
    uploadField: "Select Payment Slip *",
    uploadIdle: ["Upload a file", "or drag and drop"],
    uploadFormats: "JPG, PNG, PDF, DOCX up to 10MB",
    uploadSelected: "Selected: {filename} ({size} MB)",
    submit: "Submit Payment Slip",
    back: "Back to Payment Options",
    notesTitle: "Important Notes",
    notes: [
      "Ensure the payment slip is clear and all details are visible",
      "The payment slip will be verified within 2-3 business days",
      "Accepted formats: JPG, PNG, PDF, DOCX (Max 10MB)",
    ],
  },
  payhere: {
    step: "Step 3 of 3",
    pageLabel: "Card Payment",
    title: "Secure Card Payment",
    subtitle: "Complete your registration",
    detailsTitle: "Payment Details",
    labels: {
      registrationId: "Registration ID",
      studentName: "Student Name",
      selectedDiploma: "Selected Bootcamp(s)",
      totalAmount: "Total Amount",
      amount: "LKR 3,000 per program",
    },
    ctaTitle: "Complete Your Payment",
    ctaBody: "Click the button below to proceed with secure payment",
    ctaButton: "Pay Securely with PayHere",
    secureGateway: "Secure Payment Gateway",
    back: "Back to Payment Options",
    securityTitle: "Secure Payment",
    securityLines: [
      "Your payment is secured with SSL encryption",
      "All credit/debit card information is handled securely by PayHere",
      "We do not store your card details",
    ],
    alerts: {
      cancelled:
        "Payment was cancelled. You can try again or choose another payment method.",
      failed: "Payment failed: {error}. Please try again or contact support.",
    },
  },
  paymentSuccess: {
    completedTitle: "Payment Successful",
    processingTitle: "Payment Processing",
    completedStep: "Step 3 of 3 - Complete!",
    processingStep: "Step 3 of 3 - Processing",
    completedHeading: "Congratulations!",
    completedSubheading: "Payment Successful!",
    completedWelcome: "Welcome to the program, {{ $student->full_name }}",
    processingHeading: "Payment Processing...",
    processingBody:
      "We are verifying your payment. This usually takes a few seconds.",
    processingRefresh: "Auto-refreshing in 5s...",
    processingAction: "Check Status Now",
    registrationCardTitle: "Registration ID",
    registrationCardSubtitle: "Your Registration ID",
    registrationCardBody:
      "Keep this ID safe - you’ll need it for all communications",
    paymentCardTitle: "Payment Confirmation",
    paymentLabels: {
      status: "Payment Status",
      completed: "COMPLETED",
      processing: "PROCESSING",
      orderId: "Order ID",
      amountPaid: "Amount Paid",
      paymentDate: "Payment Date",
      pending: "Pending",
    },
    detailsTitle: "Registration Details",
    detailsLabels: {
      studentName: "Student Name",
      selectedCourse: "Selected Bootcamp(s)",
      diplomaPrefix: "",
      email: "Email",
      whatsapp: "WhatsApp",
    },
    nextStepsTitle: "What’s Next?",
    nextSteps: [
      [
        "Check Your Phone",
        "Confirmation details will be sent via a text message",
      ],
      [
        "Course Materials",
        "You’ll receive materials through the course WhatsApp group",
      ],
      ["Class Schedule", "Our team will contact you with start date"],
      ["Keep Your ID", "Use your Registration ID for all communications"],
    ],
    buttons: {
      receipt: "Download Receipt",
      retry: "Retry Payment",
      home: "Back to Home",
    },
    whatsappTitle: "Join WhatsApp Group",
    whatsappBody:
      "Click the button above to join your course-specific WhatsApp group",
    supportTitle: "Need Assistance?",
    supportBody: "Our support team is here to help you",
  },
  slipSuccess: {
    step: "Step 3 of 3 - Under Review",
    statusSteps: ["Details", "Payment", "Pending"],
    title: "Congratulations!",
    subtitle: "Your payment slip has been uploaded successfully",
    reviewTitle: "Payment Under Review",
    importantTitle: "Important Information",
    reviewBullets: [
      "Your payment slip is being verified by our team",
      "Verification typically takes 2-3 business days",
      "You will receive an email confirmation once approved",
    ],
    importantBullets: [
      "Save your Registration ID: {{ $student->registration_id }}",
      "Check your messages for payment confirmation",
      "Course details will be sent after payment verification",
      "Use your Registration ID for all future communications",
    ],
    buttons: {
      home: "Back to Home",
      print: "Print Details",
    },
  },
  offerEnded: {
    title: "Registration Period Has Ended",
    subtitle: "Thank you for your interest in CCA Campus diploma programs",
    badge: "Offer Deadline Passed",
    body: "We appreciate your interest in our diploma programs. Unfortunately, the registration period for this special offer has now closed.",
    bodyFollowup:
      "But don’t worry! We have more opportunities available for you.",
    whatsappTitle: "Need More Information?",
    whatsappBody:
      "Chat with us on WhatsApp to learn about upcoming intakes and special offers",
    whatsappCta: "Contact Us on WhatsApp",
    footer: "CCA Campus - Empowering Your Future with Quality Education",
  },
  genericSuccess: {
    title: "Registration Successful!",
    welcome:
      "Welcome, {{ $student->name_with_initials ?? $student->full_name }}!",
    body: "You have successfully registered for your chosen bootcamps.",
    registrationIdTitle: "Your Registration ID",
    registrationIdBody: "Please save this ID for future reference",
    whatsappTitle: "Join Course WhatsApp Group",
    whatsappBody:
      "Get instant updates, class schedules, and connect with other students in your diploma program.",
    whatsappCta: "Join WhatsApp Group",
    nextStepsTitle: "Next Steps",
    nextSteps: [
      "Check your WhatsApp for confirmation and further instructions",
      "Keep your Registration ID safe for future correspondence",
      "Our team will contact you within 2-3 business days",
    ],
    buttons: {
      home: "Back to Home",
      print: "Print Confirmation",
    },
  },
  receipt: {
    title: "PAYMENT RECEIPT",
    sections: [
      "Student Information",
      "Program Information",
      "Payment Details",
      "Course Fees Successfully Paid",
    ],
    labels: {
      registrationId: "Registration ID:",
      fullName: "Full Name:",
      nic: "NIC:",
      email: "Email:",
      contact: "Contact Number:",
      selectedProgram: "Selected Program:",
      paymentMethod: "Payment Method:",
      paymentMethodValue: "Online Payment (PayHere)",
      paymentStatus: "Payment Status:",
      paymentStatusValue: "Completed",
      paymentDate: "Payment Date:",
    },
    footer:
      "This is a computer-generated receipt and does not require a signature.",
  },
};
